#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Term-ReadPassword
Version  : 0.11
Release  : 4
URL      : https://cpan.metacpan.org/authors/id/P/PH/PHOENIX/Term-ReadPassword-0.11.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/P/PH/PHOENIX/Term-ReadPassword-0.11.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libt/libterm-readpassword-perl/libterm-readpassword-perl_0.11-3.debian.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Artistic-1.0 GPL-1.0
Requires: perl-Term-ReadPassword-license = %{version}-%{release}
BuildRequires : buildreq-cpan

%description
This module is in alpha-testing. Build in the usual way; send bug reports
and patches to me at the address below. From the documentation:

%package dev
Summary: dev components for the perl-Term-ReadPassword package.
Group: Development
Provides: perl-Term-ReadPassword-devel = %{version}-%{release}

%description dev
dev components for the perl-Term-ReadPassword package.


%package license
Summary: license components for the perl-Term-ReadPassword package.
Group: Default

%description license
license components for the perl-Term-ReadPassword package.


%prep
%setup -q -n Term-ReadPassword-0.11
cd ..
%setup -q -T -D -n Term-ReadPassword-0.11 -b 1
mkdir -p deblicense/
mv %{_topdir}/BUILD/debian/* %{_topdir}/BUILD/Term-ReadPassword-0.11/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/perl-Term-ReadPassword
cp deblicense/copyright %{buildroot}/usr/share/package-licenses/perl-Term-ReadPassword/deblicense_copyright
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/vendor_perl/5.28.1/Term/ReadPassword.pm

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/Term::ReadPassword.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/perl-Term-ReadPassword/deblicense_copyright
